export const signatureMeals = [
  {
    name: "Grilled Chicken Tossed Rice Bowl",
    price: 180,
    image: "/chicken-bowl.png",
    badge: "Bestseller",
    desc: "Classic comfort: Savory flavoured tossed rice paired with tender grilled chicken and a crisp fresh salad.",
    protein: "32g",
    calories: "420",
    carbs: "45g",
  },
  {
    name: "Lemon Garlic Chicken Tossed Rice Bowl",
    price: 180,
    image: "/chicken-bowl.png",
    badge: null,
    desc: "Zesty and aromatic: Marinated lemon garlic chicken served with flavoured tossed rice and garden-fresh greens.",
    protein: "34g",
    calories: "410",
    carbs: "42g",
  },
  {
    name: "Vietnamese Chicken Tossed Rice Bowl",
    price: 200,
    image: "/vietnamese-bowl.png",
    badge: "Popular",
    desc: "Exotic flair: Lemongrass-infused chicken over flavoured tossed rice with a side of refreshing salad.",
    protein: "30g",
    calories: "440",
    carbs: "48g",
  },
  {
    name: "Thai Satay Chicken Tossed Rice Bowl",
    price: 220,
    image: "/vietnamese-bowl.png",
    badge: null,
    desc: "Bold flavors: Nutty Thai satay glazed chicken with flavoured tossed rice and a crunchy fresh salad.",
    protein: "33g",
    calories: "460",
    carbs: "50g",
  },
  {
    name: "Beef Keema Tossed Rice Bowl",
    price: 180,
    image: "/hero-bowl.png",
    badge: null,
    desc: "Rich and hearty: Spiced lean beef keema served with flavoured tossed rice and a vibrant fresh salad.",
    protein: "35g",
    calories: "430",
    carbs: "44g",
  },
  {
    name: "Grilled Fish Tossed Rice Bowl",
    price: 180,
    image: "/fish-bowl.png",
    badge: "Omega-3 Rich",
    desc: "Clean nutrition: Delicate grilled fish fillet with flavoured tossed rice and a nutrient-dense salad.",
    protein: "28g",
    calories: "380",
    carbs: "40g",
  },
  {
    name: "Lemon Garlic Fish Tossed Rice Bowl",
    price: 199,
    image: "/fish-bowl.png",
    badge: null,
    desc: "Bright and light: Zesty citrus fish paired with flavoured tossed rice and a crisp garden salad.",
    protein: "30g",
    calories: "390",
    carbs: "43g",
  },
];

export const premiumMeals = [
  {
    name: "Butter Garlic Chicken Power Bowl",
    price: 230,
    included: "Mash + Veggies",
    image: "/premium-bowl.png",
    badge: "Premium",
    desc: "Indulgent yet healthy: Rich butter garlic chicken served with creamy mash and steamed seasonal veggies.",
    protein: "42g",
    calories: "520",
    carbs: "48g",
  },
  {
    name: "Beef Keema + Hummus Protein Bowl",
    price: 260,
    included: "Roti + Veggies",
    image: "/premium-bowl.png",
    badge: "High Protein",
    desc: "Protein powerhouse: Spiced beef keema with house-made hummus, soft roti, and a mix of fresh veggies.",
    protein: "48g",
    calories: "540",
    carbs: "42g",
  },
  {
    name: "Lemon Garlic Fish Power Bowl",
    price: 260,
    included: "Greek Salad + Tzatziki",
    image: "/fish-bowl.png",
    badge: "Premium",
    desc: "Mediterranean vibes: Zesty fish served with a loaded Greek salad and cool, refreshing tzatziki dip.",
    protein: "38g",
    calories: "480",
    carbs: "44g",
  },
  {
    name: "Vietnamese Chicken Deluxe Bowl",
    price: 260,
    included: "Mash + Greek Salad + Baba Ganoush",
    image: "/vietnamese-bowl.png",
    badge: "Deluxe",
    desc: "The ultimate feast: Vietnamese chicken with creamy mash, a crisp Greek salad, and smoky baba ganoush.",
    protein: "36g",
    calories: "470",
    carbs: "52g",
  },
  {
    name: "Vietnamese Chicken + Eggplant + Beans Bowl",
    price: 240,
    included: "Premium Sides",
    image: "/vietnamese-bowl.png",
    badge: null,
    desc: "Wholesome goodness: Lemongrass chicken paired with roasted eggplant, sautéed beans, and deluxe sides.",
    protein: "32g",
    calories: "450",
    carbs: "50g",
  },
  {
    name: "Chicken Hummus Mediterranean Bowl",
    price: 280,
    included: "Greek Salad + Roti",
    image: "/mediterranean-bowl.png",
    badge: "Chef's Pick",
    desc: "Signature delight: Tender chicken with silky hummus, authentic Greek salad, and warm roti.",
    protein: "44g",
    calories: "530",
    carbs: "46g",
  },
  {
    name: "Chinese Chicken Protein Bowl",
    price: 240,
    included: "Omelette + Salad + Garlic Dip",
    image: "/premium-bowl.png",
    badge: null,
    desc: "Asian fusion: Wok-tossed chicken with a fluffy omelette, fresh salad, and our signature garlic dip.",
    protein: "40g",
    calories: "460",
    carbs: "44g",
  },
];

export const addOns = [
  { name: "Extra Protein (50g)", price: 70, icon: "💪" },
  { name: "Double Protein", price: 120, icon: "⚡" },
  { name: "Extra Rice", price: 30, icon: "🌾" },
  { name: "Extra Salad", price: 30, icon: "🥗" },
  { name: "Greek Salad Upgrade", price: 60, icon: "🏛️" },
];
