export const signatureMeals = [
  {
    name: "Grilled Chicken Tossed Rice Bowl",
    price: 180,
    image: "/chicken-bowl.png",
    badge: "Bestseller",
    desc: "Tender grilled chicken breast on a bed of seasoned rice with fresh greens and our signature sauce.",
    protein: "32g",
    calories: "420",
    carbs: "45g",
  },
  {
    name: "Lemon Garlic Chicken Rice Bowl",
    price: 180,
    image: "/chicken-bowl.png",
    badge: null,
    desc: "Zesty lemon garlic marinated chicken with aromatic jasmine rice and crunchy vegetables.",
    protein: "34g",
    calories: "410",
    carbs: "42g",
  },
  {
    name: "Vietnamese Chicken Rice Bowl",
    price: 200,
    image: "/vietnamese-bowl.png",
    badge: "Popular",
    desc: "Lemongrass-infused chicken with pickled veggies, fresh herbs, and crushed peanuts.",
    protein: "30g",
    calories: "440",
    carbs: "48g",
  },
  {
    name: "Thai Satay Chicken Rice Bowl",
    price: 220,
    image: "/vietnamese-bowl.png",
    badge: null,
    desc: "Rich peanut satay glaze over tender chicken with coconut-lime rice and bean sprouts.",
    protein: "33g",
    calories: "460",
    carbs: "50g",
  },
  {
    name: "Beef Keema Tossed Rice Bowl",
    price: 180,
    image: "/hero-bowl.png",
    badge: null,
    desc: "Lean spiced beef keema with turmeric rice, raita drizzle, and fresh mint.",
    protein: "35g",
    calories: "430",
    carbs: "44g",
  },
  {
    name: "Grilled Fish Tossed Rice Bowl",
    price: 180,
    image: "/fish-bowl.png",
    badge: "Omega-3 Rich",
    desc: "Delicate grilled fish fillet with sesame rice, edamame, and ginger-soy dressing.",
    protein: "28g",
    calories: "380",
    carbs: "40g",
  },
  {
    name: "Lemon Garlic Fish Rice Bowl",
    price: 199,
    image: "/fish-bowl.png",
    badge: null,
    desc: "Citrus-herb marinated fish with brown rice, roasted sweet potato, and microgreens.",
    protein: "30g",
    calories: "390",
    carbs: "43g",
  },
];

export const premiumMeals = [
  {
    name: "Butter Garlic Chicken Power Bowl",
    price: 230,
    image: "/premium-bowl.png",
    badge: "Premium",
    desc: "Rich butter garlic chicken with power grains, roasted chickpeas, and tahini drizzle.",
    protein: "42g",
    calories: "520",
    carbs: "48g",
  },
  {
    name: "Beef Keema + Hummus Protein Bowl",
    price: 260,
    image: "/premium-bowl.png",
    badge: "High Protein",
    desc: "Spiced lean beef with house-made hummus, quinoa, and grilled Mediterranean vegetables.",
    protein: "48g",
    calories: "540",
    carbs: "42g",
  },
  {
    name: "Lemon Garlic Fish Power Bowl",
    price: 260,
    image: "/fish-bowl.png",
    badge: "Premium",
    desc: "Herb-crusted fish with power grains, avocado, kale, and lemon-tahini dressing.",
    protein: "38g",
    calories: "480",
    carbs: "44g",
  },
  {
    name: "Vietnamese Chicken Deluxe Bowl",
    price: 260,
    image: "/vietnamese-bowl.png",
    badge: "Deluxe",
    desc: "Elevated Vietnamese chicken with vermicelli, extra herbs, crispy shallots, and nuoc cham.",
    protein: "36g",
    calories: "470",
    carbs: "52g",
  },
  {
    name: "Vietnamese Chicken + Eggplant Bowl",
    price: 240,
    image: "/vietnamese-bowl.png",
    badge: null,
    desc: "Smoky grilled eggplant paired with lemongrass chicken, jasmine rice, and Thai basil.",
    protein: "32g",
    calories: "450",
    carbs: "50g",
  },
  {
    name: "Chicken Hummus Mediterranean Bowl",
    price: 280,
    image: "/mediterranean-bowl.png",
    badge: "Chef's Pick",
    desc: "Grilled chicken with house hummus, falafel bites, tabbouleh, and pomegranate molasses.",
    protein: "44g",
    calories: "530",
    carbs: "46g",
  },
  {
    name: "Chinese Chicken Protein Bowl",
    price: 240,
    image: "/premium-bowl.png",
    badge: null,
    desc: "Wok-tossed chicken in light soy-ginger sauce with brown rice and steamed bok choy.",
    protein: "40g",
    calories: "460",
    carbs: "44g",
  },
];
